In [59]:
import pandas as pd
import numpy as np

In [ ]:
# load the data
#import os
#os.getcwd()
df = pd.read_csv('../data/car_fuel_efficiency.csv')


## Question 1. Pandas version
What's the version of Pandas that you installed?

In [ ]:
pd.__version__

'2.3.2'

## Question 2. Records count
How many records are in the dataset?


In [8]:
df.shape[0]

9704

## Question 3. Fuel types
How many fuel types are presented in the dataset?

In [10]:
df['fuel_type'].nunique()

2

## Question 4. Missing values
How many columns in the dataset have missing values?

In [17]:
sum(df.isnull().sum() > 0)

4

## Question 5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [26]:
round(df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max(), 2)

23.76

## Question 6. Median value of horsepower
1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?

In [44]:
med = df.horsepower.median()
med

149.0

In [28]:
most_freq = df.horsepower.mode()
most_freq

0    152.0
Name: horsepower, dtype: float64

In [42]:
med_impute = df.horsepower.fillna(value=most_freq[0]).median()
med_impute

152.0

In [ ]:
# change in median after imputation using most frequent value
med_impute - med

3.0

## Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

In [103]:
X = df[['vehicle_weight', 'model_year']].head(7)

In [104]:
XTX = X.T.dot(X)

In [105]:
XTX


vehicle_weight    model_year
vehicle_weight    6.470773e+07  4.247135e+07
model_year        4.247135e+07  2.826475e+07

In [112]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.12464107e-06, -1.68991495e-06],
       [-1.68991495e-06,  2.57468996e-06]])

In [107]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [110]:
#w = (XTX_inv * X.T)
w = (XTX_inv.dot(X.transpose())).dot(y)
w

array([0.07099685, 0.41931263])

In [115]:
round(w.sum(),4)

np.float64(0.4903)

In [132]:
# check coefficents match 
from sklearn.linear_model import LinearRegression

regressor = LinearRegression(fit_intercept=False).fit(X, y)

regressor.coef_


array([0.07099685, 0.41931263])

In [ ]:
round(regressor.coef_.sum(),2)

np.float64(0.49)