In [3]:
import numpy as np

In [5]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [2]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [6]:
vector_vector_multiplication(u, v)

np.float64(110.0)

In [9]:
v.dot(u)

np.int64(110)

In [39]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [10]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [25]:
V = np.array([
    [1, 2, 4],
    [4, 5, 7] ])
V

array([[1, 2, 4],
       [4, 5, 7]])

In [38]:
V.shape

(2, 3)

In [32]:
U = np.array([
    [2],
    [2],
    [2]])
U

array([[2],
       [2],
       [2]])

In [37]:
U.shape

(3, 1)

In [41]:
matrix_matrix_multiplication(V, U)

array([[14.],
       [32.]])

In [42]:
V.dot(U)

array([[14],
       [32]])

In [43]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
A = np.array([
    [1, 2, 4],
    [4, 5, 7],
    [7, 6, 9] ])
A

array([[1, 2, 4],
       [4, 5, 7],
       [7, 6, 9]])

In [50]:
# Inverse (:= A . A^-1 = I)
A_inv = np.linalg.inv(A)
A_inv

In [52]:
A_inv.dot(A)

array([[ 1.00000000e+00,  3.33066907e-16,  4.99600361e-16],
       [ 9.99200722e-16,  1.00000000e+00, -1.11022302e-16],
       [ 2.77555756e-16,  5.55111512e-16,  1.00000000e+00]])