In [3]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
a = np.array([1, 2, 3, 5,7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]

np.int64(3)

In [9]:
# Multi-dim array
# 5 x 2
np.zeros((5,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
n = np.array([
    [0, 1, 3],
    [4, 5, 6],
    [7, 8, 9]])
n

array([[0, 1, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# row 1
n[0]

array([0, 1, 3])

In [13]:
# column 2
# `:` return everythin
n[:, 1]

array([1, 5, 8])

In [16]:
# random (standard normal)
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [17]:
# random integers
np.random.randint(low=0, high=100, size=(5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

In [18]:
# summarziation
n.std()

np.float64(2.8974232912011773)

In [19]:
n.mean()

np.float64(4.777777777777778)